services:

  postgres:
    image: postgres:13.4
    restart: always
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - ./db_setup:/docker-entrypoint-initdb.d
      - ./pg_data:/var/lib/postgresql/data