spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: admin
    password: admin
    initialization-mode: never
  jpa:
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.xml
    contexts: local

management:
  endpoints:
    web:
      exposure:
        include: actuator,beans,health,integrationgraph,liquibase,mappings,metrics,threaddump
    enabled-by-default: true

aws:
  sqs:
    queueUrl: http://localhost:4566/000000000000/productmanagement-shared-dde-poms-sync-admin-entities-queue.fifo
  sns:
    topicArn: arn:aws:sns:us-east-1:000000000000:productmanagement-shared-dde-poms-core-all-entities-topic.fifo
